export const REKIT_TOOLS_RUN_BUILD_BEGIN = 'REKIT_TOOLS_RUN_BUILD_BEGIN';
export const REKIT_TOOLS_RUN_BUILD_SUCCESS = 'REKIT_TOOLS_RUN_BUILD_SUCCESS';
export const REKIT_TOOLS_RUN_BUILD_FAILURE = 'REKIT_TOOLS_RUN_BUILD_FAILURE';
export const REKIT_TOOLS_RUN_BUILD_DISMISS_ERROR = 'REKIT_TOOLS_RUN_BUILD_DISMISS_ERROR';
